kind: pipeline
type: docker
name: default

steps:
  - name: install_dependencies
    image: node:16
    commands:
      - npm install
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: lint
    image: node:16
    commands:
      - npm run lint -- --max-warnings 10
    environment:
      DRONE_DEBUG: true
    timeout: 5m
    resources:
      limits:
        memory: 1GiB
        cpu: 1

  - name: test_unit
    image: node:16
    commands:
      - npm run test:unit
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: test_integration
    image: node:16
    commands:
      - npm run test:integration
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: build
    image: node:16
    commands:
      - npm run build
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: docker_build
    image: plugins/docker
    settings:
      repo: your-docker-repo/undercovergame
      tags: latest

  - name: deploy_test
    image: appleboy/drone-ssh
    settings:
      host: your_test_server
      username: your_username
      password: your_password
      script:
        - docker pull your-docker-repo/undercovergame:latest
        - docker stop undercovergame_test || true
        - docker rm undercovergame_test || true
        - docker run -d --name undercovergame_test -p 3000:3000 your-docker-repo/undercovergame:latest

  - name: deploy_prod
    image: appleboy/drone-ssh
    settings:
      host: your_prod_server
      username: your_username
      password: your_password
      script:
        - docker pull your-docker-repo/undercovergame:latest
        - docker stop undercovergame_prod || true
        - docker rm undercovergame_prod || true
        - docker run -d --name undercovergame_prod -p 3000:3000 your-docker-repo/undercovergame:latest

services:
  - name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: game-database
