kind: pipeline
type: docker
name: default

steps:
  - name: install_dependencies
    image: node:16
    commands:
      - npm install
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: lint
    image: node:16
    commands:
      - npm install eslint --save-dev
      - npm run lint -- --max-warnings 10 || true
    environment:
      DRONE_DEBUG: true
    timeout: 5m
    resources:
      limits:
        memory: 1GiB
        cpu: 1

  - name: make_tests_executable
    image: node:16
    commands:
      - chmod +x test/unit/.test.cjs
      - chmod +x test/integration/.test.cjs

  - name: start_server_and_test_integration
    image: node:16
    commands:
      - node server.js &  # Start server i baggrunden
      - sleep 5  # Vent 5 sekunder for at sikre, at appen starter
      - npm run test:integration  # Kør integrationstest
    environment:
      DRONE_DEBUG: true
    timeout: 15m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: test_unit
    image: node:16
    commands:
      - npm run test:unit
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: build
    image: node:16
    commands:
      - npm run build
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: install_sonarscanner
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet tool install --global dotnet-sonarscanner

  - name: sonar_begin
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
    commands:
      - /root/.dotnet/tools/dotnet-sonarscanner begin /k:"easv-devops_UndercoverSpillet_AY_Gm45-EVvRW2O60GUR" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token="${SONAR_TOKEN}"

  - name: build_dotnet
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet build

  - name: sonar_end
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
    commands:
      - /root/.dotnet/tools/dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"

  - name: docker_build
    image: plugins/docker
    settings:
      repo: yonesswaidan/undercovergame
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

services:
  - name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: game-database

secrets:
  - name: docker_username
  - name: docker_password
  - name: SONAR_TOKEN
