---
kind: pipeline
type: docker
name: integration

steps:
  - name: fix_permissions
    image: node:16
    commands:
      - chown -R 1000:1000 /drone/src

  - name: kode-analyse
    image: sonarsource/sonar-scanner-cli
    commands:
      - sonar-scanner -Dsonar.projectKey=easv-devops_UndercoverSpillet_AY_JUDVyEVvRW2O60GX5 -Dsonar.sources=. -Dsonar.host.url=http://sonar.setgo.dk:9000 -Dsonar.login=$SONAR_TOKEN
    environment:
      SONAR_TOKEN:
        from_secret: sonarqube_token
    depends_on:
      - fix_permissions

  - name: gør_tests_eksekverbare
    image: node:16
    commands:
      - chmod +x test/unit/.test.cjs
      - chmod +x test/integration/.test.cjs
    depends_on:
      - kode-analyse

  - name: test_unit
    image: node:16
    commands:
      - npm run test:unit
    environment:
      DRONE_DEBUG: "true"
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2
    depends_on:
      - gør_tests_eksekverbare

  - name: start_server_og_test_integration
    image: node:16
    commands:
      - node server.js &  # Start serveren i baggrunden
      - sleep 5  # Vent 5 sekunder for at sikre, at appen starter
      - npm run test:integration  # Kør integrationstest
    environment:
      DRONE_DEBUG: true
    timeout: 15m
    resources:
      limits:
        memory: 2GiB
        cpu: 2
    depends_on:
      - test_unit

  - name: lint
    image: node:16
    commands:
      - npm install eslint eslint-plugin-import eslint-plugin-node eslint-config-airbnb-base --save-dev
      - chmod +x ./node_modules/.bin/eslint
      - npm run lint -- --max-warnings 10 || true
    environment:
      DRONE_DEBUG: "true"
    timeout: 5m
    resources:
      limits:
        memory: 1GiB
        cpu: 1
    depends_on:
      - start_server_og_test_integration

---
kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish_api
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: yonesswaidan/undercovergame-api
      tags:
        - latest

  - name: publish_web
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: yonesswaidan/undercovergame-web
      tags:
        - latest

  - name: performance_tests
    image: grafana/k6
    commands:
      - k6 run test/performance/load_test.js
      - k6 run test/performance/spike_test.js
      - k6 run test/performance/stress_test.js
    depends_on:
      - publish_web

---
kind: pipeline
type: docker
name: deploy
depends_on:
  - deliver

steps:
  - name: release_api
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: yonesswaidan/undercovergame-api
      tags:
        - production

  - name: release_web
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: yonesswaidan/undercovergame-web
      tags:
        - production

services:
  - name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: game-database

secrets:
  - name: docker_username
  - name: docker_password
  - name: sonarqube_token
