kind: pipeline
type: docker
name: default

steps:
  - name: install_dependencies
    image: node:16
    commands:
      - npm install
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: lint
    image: node:16
    commands:
      - npm install eslint --save-dev
      - npm run lint -- --max-warnings 10 || true
    environment:
      DRONE_DEBUG: true
    timeout: 5m
    resources:
      limits:
        memory: 1GiB
        cpu: 1

  - name: make_tests_executable
    image: node:16
    commands:
      - chmod +x test/unit/.test.cjs

  - name: test_unit
    image: node:16
    commands:
      - npm run test:unit
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: test_integration
    image: node:16
    commands:
      - npm run test:integration
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: build
    image: node:16
    commands:
      - npm run build
    environment:
      DRONE_DEBUG: true
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: docker_build
    image: plugins/docker
    settings:
      repo: yonesswaidan/undercovergame
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy_test
    image: plugins/docker
    settings:
      repo: yonesswaidan/undercovergame:test
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy_prod
    image: plugins/docker
    settings:
      repo: yonesswaidan/undercovergame:prod
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: watchtower_test
    image: containrrr/watchtower
    settings:
      repo: yonesswaidan/undercovergame:test
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      run_once: true

  - name: watchtower_prod
    image: containrrr/watchtower
    settings:
      repo: yonesswaidan/undercovergame:prod
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      run_once: true

services:
  - name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: game-database
