kind: pipeline
type: docker
name: default

steps:
  - name: install_dependencies
    image: node:16
    environment:
      DRONE_DEBUG: true
    commands:
      - npm install
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: lint
    image: node:16
    environment:
      DRONE_DEBUG: true
    commands:
      - npm run lint -- --max-warnings 10
    timeout: 5m
    resources:
      limits:
        memory: 1GiB
        cpu: 1

  - name: test_unit
    image: node:16
    environment:
      DRONE_DEBUG: true
    commands:
      - npm run test:unit
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: test_integration
    image: node:16
    environment:
      DRONE_DEBUG: true
    commands:
      - npm run test:integration
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: build
    image: node:16
    environment:
      DRONE_DEBUG: true
    commands:
      - npm run build
    timeout: 10m
    resources:
      limits:
        memory: 2GiB
        cpu: 2

  - name: docker_build
    image: plugins/docker
    settings:
      repo: your-docker-repo/navnegruppenreactwebsite
      tags: latest

  - name: deploy_test
    image: appleboy/drone-ssh
    settings:
      host: your_test_server
      username: your_username
      password: your_password
      script:
        - docker pull your-docker-repo/navnegruppenreactwebsite:latest
        - docker stop navnegruppen_test || true
        - docker rm navnegruppen_test || true
        - docker run -d --name navnegruppen_test -p 5173:5173 your-docker-repo/navnegruppenreactwebsite:latest

  - name: deploy_prod
    image: appleboy/drone-ssh
    settings:
      host: your_prod_server
      username: your_username
      password: your_password
      script:
        - docker pull your-docker-repo/navnegruppenreactwebsite:latest
        - docker stop navnegruppen_prod || true
        - docker rm navnegruppen_prod || true
        - docker run -d --name navnegruppen_prod -p 5173:5173 your-docker-repo/navnegruppenreactwebsite:latest

services:
  - name: navnegruppen-mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: NewbornNamesDB

