version: '3.8'

services:
  task-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "192.168.87.167:3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://yonesswaidan:sgg59mcd@game-database.x2asuuz.mongodb.net/game-database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  task-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "192.168.87.167:3001:3000"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://yonesswaidan:sgg59mcd@game-database.x2asuuz.mongodb.net/game-database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    build: .
    ports:
      - "192.168.87.167:3002:3000"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://yonesswaidan:sgg59mcd@game-database.x2asuuz.mongodb.net/game-database
    volumes:
      - .:/usr/src/app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mongodb:
    image: mongo:latest
    ports:
      - "192.168.87.167:27017:27017"
    volumes:
      - mongo-data:/data/db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=30

  k6:
    image: grafana/k6
    command: run /scripts/load_test.js
    volumes:
      - ./load_test.js:/scripts/load_test.js
    depends_on:
      - task-app-frontend
    networks:
      - default

volumes:
  mongo-data:
